# Generated by Django 5.0.6 on 2024-07-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_houselisting_zipcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HouseListing',
        ),
    ]
