# Generated by Django 5.0.6 on 2024-07-10 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zipcode', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('LotArea', models.FloatField()),
                ('Utilities', models.CharField(max_length=255)),
                ('BldgType', models.CharField(choices=[('1Fam', 'Single-family'), ('2FmCon', 'Apartment building'), ('TwnhsE', 'Townhouse end unit'), ('TwnhsI', 'Townhouse inside unit')], max_length=255)),
                ('LotConfig', models.CharField(blank=True, choices=[('Inside', 'Inside lot'), ('Corner', 'Corner lot'), ('CulDSac', 'Cul-de-Sac'), ('FR2', 'Frontage on 2 sides')], max_length=255, null=True)),
                ('LandSlope', models.CharField(blank=True, choices=[('Gtl', 'Slight slope'), ('Mod', 'Moderate slope'), ('Sev', 'Severe slope')], max_length=255, null=True)),
                ('predicted_price', models.FloatField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
