# Generated by Django 5.0.6 on 2024-07-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_houselisting_bedroomabvgr_houselisting_bsmtunfsf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houselisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='house_images/'),
        ),
    ]
