# Generated by Django 5.0.6 on 2024-07-14 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_houselisting_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houselisting',
            name='LandSlope',
        ),
    ]
