# Generated by Django 5.0.6 on 2024-07-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_remove_houselisting_landslope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houselisting',
            name='image',
        ),
        migrations.AddField(
            model_name='houselisting',
            name='HouseImage',
            field=models.ImageField(blank=True, null=True, upload_to='house_images/', verbose_name='House Image'),
        ),
    ]
